### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'datetime.timedelta' and 'float'

### ISSUE THREAD

**Issue by az0** [dionysio/hillary_clinton_email_generator#1]
```
$ python2 generate_emails.py 
Traceback (most recent call last):
  File "generate_emails.py", line 74, in <module>
    generate_emails(**dict(args.__dict__))
  File "generate_emails.py", line 59, in generate_emails
    for message in _generate_emails(number_of_emails, content_model_path, subject_model_path, **kwargs):
  File "generate_emails.py", line 52, in _generate_emails
    yield _generate_email(subject_model, content_model, number_of_sentences=number_of_sentences)
  File "generate_emails.py", line 42, in _generate_email
    message['Sent'] = _get_random_datetime()
  File "generate_emails.py", line 25, in _get_random_datetime
    return (start + (end - start) * random.random()).strftime('%A, %B %d, %Y %I:%M %p')  # Saturday, September 15, 2012 2:20 PM
TypeError: unsupported operand type(s) for *: 'datetime.timedelta' and 'float'

```

**Comment by az0** [comment]
fixed
