### ISSUE TITLE
SyntaxError: Non-ASCII character

### ISSUE THREAD

**Issue by az0** [dionysio/hillary_clinton_email_generator#2]
```
$ python2 generate_emails.py 
Traceback (most recent call last):
  File "generate_emails.py", line 8, in <module>
    from generate_model import load_content_model, load_subject_model, BASE_PATH, CONTENT_MODEL_PATH, SUBJECT_MODEL_PATH, get_recipients
  File "/tmp/hillary_clinton_email_generator/generate_model.py", line 31
SyntaxError: Non-ASCII character '\xc2' in file /tmp/hillary_clinton_email_generator/generate_model.py on line 31, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by az0** [comment]
fixed
